services:
  valkey:
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    container_name: searxng-valkey
    volumes:
      - ${SEARXNG_VALKEY_DATA_FOLDER:-./searxng-valkey_data}:/data
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${SEARXNG_VALKEY_IP_ADDRESS}

  searxng:
    image: searxng/searxng
    container_name: searxng-app
    volumes:
      - ${SEARXNG_CONFIG_FOLDER:-./config}:/etc/searxng
      - ${SEARXNG_DATA_FOLDER:-./data}:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-false}
      - SEARXNG_VALKEY_URL=${SEARXNG_VALKEY_URL:-false}
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - SEARXNG_LIMITER=${SEARXNG_LIMITER:-false}
      - SEARXNG_IMAGE_PROXY=${SEARXNG_IMAGE_PROXY:-false}
    restart: unless-stopped
    depends_on:
      - valkey
    networks:
      external:
        ipv4_address: ${SEARXNG_IP_ADDRESS}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}